version: '3'


services:
  backend:
    build: .
    container_name: news_backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    container_name: news_db
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
